package com.mar2sdk.core.ad.status

enum class ShowFailResult {
	LOAD_FAILED,
	LOAD_TIMEOUT,
	OTHER_AD_IS_SHOWING,
	OTHER_AD_OCCUR,
	ACTIVITY_IS_FINISHING,
	FAILED_TO_SHOW_CONTENT,
	SHOW_AD_EXCEPTION
}